name: Deploy NestJS App

on:
  push:
    branches:
      - main # faqat main branchga push bo‘lsa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/computer-logs
            git pull origin main
            npm install --production
            npm run build
            pm2 describe computer-logs > /dev/null && pm2 restart computer-logs || pm2 start dist/main.js --name computer-logs
